# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en"
pipeline:
  - name: HFTransformersNLP
    model_weights: "bert-base-uncased"
    model_name: "bert"
    cache_dir: /tmp
  - name: LanguageModelTokenizer
    intent_tokenization_flag: True
    intent_split_symbol: "+"
  - name: sentiment_analyzer.SentimentAnalyzer
  - name: LanguageModelFeaturizer
  - name: RegexFeaturizer
  - name: DIETClassifier
    epochs: 150
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
#  - name: TwoStageFallbackPolicy
#    nlu_threshold: 0.3
#    core_threshold: 0.3
#    fallback_core_action_name: "action_default_fallback"
#    fallback_nlu_action_name: "action_default_fallback"
#    deny_suggestion_intent_name: "out_of_scope"
